apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: order-service-ns
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

    scrape_configs:
      - job_name: 'otel-collector'
        http_sd_configs: []
        static_configs:
          - targets: ['otel-collector:8889']

            #      - job_name: 'order-service'
            #        metrics_path: /actuator/prometheus   # <-- updated to match Spring Boot base path
            #        static_configs:
            #          - targets: ['order-service-svc:8080']

